apply enable_public_net_ipv4 and enable_public_net_ipv6 to autoscaler configuration
vitobotta/hetzner-k3s pull request #381
Opened 2024-07-19 16:31 UTC by Funzinator

fixes #372

2024-07-20 10:13 UTC, vitobotta requested changes
Hi! Thanks a lot. See comment - if you can test that change it would be great :)

2024-07-20 10:13 UTC, vitobotta commented on src/kubernetes/software/cluster_autoscaler.cr
> +    set_container_environment_variable(autoscaler_container, "HCLOUD_PUBLIC_IPV6", settings.enable_public_net_ipv6 ? "true" : "false")
Hi, thanks for the PR! Those settings are already booleans, so you should be able to do 

```suggestion
    set_container_environment_variable(autoscaler_container, "HCLOUD_PUBLIC_IPV4", settings.enable_public_net_ipv4.to_s)
    set_container_environment_variable(autoscaler_container, "HCLOUD_PUBLIC_IPV6", settings.enable_public_net_ipv6.to_s)
```

2024-07-24 19:51 UTC, Funzinator commented
Ah, learned something new about Crystal :-)...
That works equally well. Amended my commit.

2024-07-24 20:42 UTC, merged

2024-07-24 20:42 UTC, vitobotta commented
Thanks!

2024-07-24 20:44 UTC, vitobotta commented
I also merged it into the v2 branch as well :)

2024-07-24 20:45 UTC, benkrej commented
Thank you for fixing!